name: doc
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install poetry==1.1.4
        poetry install --no-dev --extras doc
    - name: Deploy doc
      run: poetry run mkdocs gh-deploy --force