name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install poetry==1.1.4
        poetry install
    - name: Testing
      run: poetry run pytest --cov=bgraph
